apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  labels:
    app: notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: prathyand/thebitbeta:notification_service_latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "96Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq-0.rabbitmq.rabbits.svc.cluster.local"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: QUEUE_NAME
          value: "email_worker_queue&reset_password_queue"
        tty: true
        

